# This is a basic workflow to help you get started with Actions

name: HCP Terraform Notification

# Controls when the workflow will run
on:
  repository_dispatch:
    types:
      - hcp-terraform-workspace
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "process-payload"
  process-payload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell to extract the content of the payload
      - name: Print entire client payload
        run: echo "Client payload: ${{ toJson(github.event.workspace_data) }}"
