# This is a basic workflow to help you get started with Actions

name: HCP Terraform Notification

# Controls when the workflow will run
on:
  repository_dispatch:
    types:
      - hcp-terraform-workspace
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "process-payload"
  process-payload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Access specific fields in workspace data
        run: |
          echo "Run ID: ${{ github.event.client_payload.run_id }}"
          echo "Workspace Slug: ${{ github.event.client_payload.workspace_slug }}"
